language: go
go:
- 1.12
env:
- GO111MODULE=on
script: go vet
before_deploy:
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: lWituvF6/29wK/9C4O+l4RBFpRNFuPo56aI+ZRzneUxd1f1K0yGs/ti/bIXTNNGelbKmkg159bGLnHTETKZYS4r0EGwNqO20HxDYiBegP4ugl6qmrX6z+gEBDZXXdMOU9JCWqIBH8twbfwJltbfD1Cf7FUphgmnhWZzyUopbN7ls+PewTFdRtQXDAa22MegqvH8OrfP9Kw7JTwH+T8E7dA09D2zoJJhZJkFgHsPnRnF3k+kYxHNtQQPpnJERww1PkqPug4xjdm6JLn3mfyFae0gPAeaBDqZ20mSjNbxOVsUIxIay8jhTmspyWh/Z9S7ln8sNukA0jPLhIz+jB0oj4htDzypb9XvX1uWZGM08V66eUgEuRTx2mtrMZ8EGLKCUay0385AdYIa6N2KzNLcu1epzZGrBXwwCm45QN+IM4IDzZF2rbGMStSJ0EprkJFTmF/ee3yprn8XhBg8Lwvv0l0MSrXbFzwajL8tc60r400aGVuReQLBJsjSRfhqG41xt6CqG8rrec5pWbQkmy1/8slIMpZJNDR57Mh4ffyCCylpzGgGYg86fCrTWhwHlGJRYH2R08NX4L0HKly8Si+LwLExPnGTbPwV9Iqq6ftlUanLHYaZKVXXRBzqmodvPOsifMTet/pnHdw3jj0vq9d1rWCV4kDAt3T/toKOKYvu37Fk=
  skip_cleanup: true
  file:
    - release/cliconnect-darwin-amd64
    - release/cliconnect-darwin-amd64.sha256
    - release/cliconnect-linux-amd64
    - release/cliconnect-linux-amd64.sha256
  on:
    repo: wakeful/cliconnect
    branch: master
    tags: true
